import { FileText } from 'lucide-react';
import { Card, CardContent } from '@/components/ui/card';
import { useTranslation } from 'react-i18next';

export function UsagePolicy() {
  const { t } = useTranslation('legal');
  return (
    <div className="max-w-3xl mx-auto space-y-6">
      <div className="flex items-center gap-3">
        <FileText className="h-8 w-8 text-purple-500" />
        <h1 className="text-3xl font-bold">{t('usage.title')}</h1>
      </div>

      <Card>
        <CardContent className="pt-6 prose dark:prose-invert max-w-none">
          <p className="text-muted-foreground">Last updated: January 2026</p>

          <h2>1. Acceptable Use</h2>
          <p>Rizko.ai is designed for legitimate content creation and trend analysis. Users agree to use the platform responsibly and in compliance with all applicable laws.</p>

          <h2>2. Prohibited Activities</h2>
          <ul>
            <li>Automated scraping or data harvesting beyond platform limits</li>
            <li>Sharing account credentials with third parties</li>
            <li>Using the service for spam or misleading content</li>
            <li>Attempting to reverse engineer our algorithms</li>
          </ul>

          <h2>3. AI-Generated Content</h2>
          <p>Scripts and content generated by our AI are provided as suggestions. Users are responsible for reviewing and editing content before publishing.</p>

          <h2>4. Rate Limits</h2>
          <p>Each plan has specific usage limits. Exceeding these limits may result in temporary restrictions or account suspension.</p>

          <h2>5. Account Termination</h2>
          <p>We reserve the right to suspend or terminate accounts that violate this policy.</p>

          <p className="text-sm text-muted-foreground mt-8">This policy is subject to change. Full terms coming soon.</p>
        </CardContent>
      </Card>
    </div>
  );
}
